name: MCAntiSpawnerNameChange
version: '${project.version}'
main: dev.draco.mcantispawnernamechange.MCAntiSpawnerNameChange
api-version: 1.19
authors: [ Dracobro ]
description: A plugin designed to stop players from changing the name of a mob spawner from an anvil in Minecraft
